### ISSUE TITLE
Why is there a comparison with naiveSolver needed?

### ISSUE THREAD

**Issue by dopatraman** [jotrk/anagram-solver#1]
Why not match the solved anagram with the list of words in wordset?

**Comment by jchnkl** [comment]
There's a possibility that, if not implemented correctly, the recursive solver won't find all solutions. Hence if it finds only a subset of valid solutions, checking against the wordset will result in a proper test case for a wrong implementation. For example, given the proper solution of `"hello", "hell", "he"` checking a solution of `"hello", "hell"` against the wordset will succeed, although incomplete. Comparing it against the (complete) solution of the naive solver will reveal that it's faulty.

**Comment by dopatraman** [comment]
Maybe you could explain how the naiveSolver is supposed to work? It seems like it is building a list of words directly from the dictionary. If thats the case... wouldnt this test take hours to complete?

**Comment by jchnkl** [comment]
The `naiveSolver` is an extension of the idea on how to solve anagrams with
a fixed length using a dictionary. It basically works by generating a key for
every word in the dictionary by sorting its letters. For example, `"solver"` has
the key `"elorsv"`, and so does `"lovers"`. Next, you put all words with the
same key in a list (`("elorsv", ["solver","lovers"]`) and transform it into
a hash table. Now, whenever you want to find the anagrams for a word (e.g.
`"solver"`), you just sort its letters for the key again and look it up in the
hash table, where the list of words are all valid anagrams. There's another
explanation on [stackoverflow](https://stackoverflow.com/questions/12477339/finding-anagrams-for-a-given-word).

In order to find all sub-anagrams of a word (e.g. for `"solver"`: `["leo","rose","love", ..]`) you'll need to extend the idea above a bit. Instead of just looking up the sorted word, you now generate a list of all subsequences of that word (e.g. `"solver"`: `["s","o","so","l","sl","ol", ..]`). `Data.List.subsequences` can do this for you, but it's a bit slow, at least for long words. You'll also need to `map sort` and `nub` that list, to weed out all common occurrences. Now you have a list of all keys for sub-anagrams.

I hope it's clearer now, if not, just ask.
Anyhow, `naiveSolver` is not meant to be used anyway, I just implemented it to verify my implementation of the word graph solver.

**Comment by dopatraman** [comment]
I see, thank you for the explanation.

Where is the word graph actually generated. I see the function that is supposed to do it... I'm guessing the DAWG is constructed internally somewhere?

**Comment by jchnkl** [comment]
The DAWG is generated using the [`fromLang`](https://hackage.haskell.org/package/dawg-0.11/docs/Data-DAWG-Static.html#v:fromLang) function from the [dawg](https://hackage.haskell.org/package/dawg) package. I did not implement the DAWG myself. However, as far as I understood it, the dawg package makes use of vectors for representing the edges.
If you want to understand how a DAWG works, I recommend starting with the Wikipedia article on [DAWG](https://en.wikipedia.org/wiki/Deterministic_acyclic_finite_state_automaton)s and [Trie](https://en.wikipedia.org/wiki/Trie)s. In the case of the anagram solver, the DAWG is interchangeable with a Trie, but more space efficient. Theoretically at least, I didn't benchmark it.

**Comment by dopatraman** [comment]
Interesting. Thanks for shedding some light on this. This may be a bit off topic as far as this repo is concerned, but I'm curious as to how one would implement a Trie in Haskell. Can you point me in the right direction? A code sample would be great.

Thanks again.

**Comment by jchnkl** [comment]
There are several packages on hackage which implement Tries:
https://hackage.haskell.org/packages/search?terms=trie
They are probably a good starting point for studying source code.

You might also want to check out literature like Okasaki's Purely Functional Data Structures. I don't know if it covers Tries, but there are several PDFs available on the web which you might want to check out before getting a copy of the book.
